import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    rules: {
      // Links inside the site are plain <a> elements on purpose: every
      // navigation is a document load, with a fresh <html lang> and a fresh
      // CSP nonce (docs/design.md, header).
      "@next/next/no-html-link-for-pages": "off",
    },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Build folders of parallel dev servers (NEXT_DIST_DIR=.next-xyz):
    ".next-*/**",
    // OpenNext and wrangler output:
    ".open-next/**",
    ".wrangler/**",
    // Generated by scripts/generate-key-text.mjs:
    "src/content/keys/key-text.generated.ts",
    // Generated by scripts/generate-blog.mjs:
    "src/content/blog-generated/**",
  ]),
]);

export default eslintConfig;
